internet_shop-master/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:book_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:book_id>/', views.cart_remove, name='cart_remove'),
]

internet_shop-master/internet_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('books.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internet_shop-master/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

internet_shop-master/cart/models.py
from django.db import models

# Create your models here.

internet_shop-master/cart/forms.py
from django import forms

BOOK_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddBookForm(forms.Form):
    quantity = forms.TypedChoiceField(
        label='',
        choices=BOOK_QUANTITY_CHOICES,
        coerce=int,
        widget=forms.Select(attrs={'class': 'form-select', 'style': 'margin-bottom: 10px'})
    )
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

internet_shop-master/cart/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from books.models import Book
from .cart import Cart
from .forms import CartAddBookForm


@require_POST
def cart_add(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    form = CartAddBookForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(book=book,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    cart.remove(book)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddBookForm(initial={'quantity': item['quantity'],
                                                                'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

internet_shop-master/cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Корзина
{% endblock %}

{% block breadcrumbs %}
<nav style="--bs-breadcrumb-divider: '>'; margin-left: 20px;" aria-label="breadcrumb">
    <ol class="breadcrumb mt-3">
        <li class="breadcrumb-item active"><a href="{% url 'home' %}">Главная</a></li>
        <li class="breadcrumb-item">Корзина</li>
    </ol>
</nav>
{% endblock %}

{% block content %}

<div class="cart_section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <div class="cart_container">
                    {% for item in cart %}
                    {% with book=item.book %}
                    <div class="cart_items">
                        <ul class="cart_list">
                            <li class="cart_item clearfix">
                                <div class="d-flex flex-md-row flex-column justify-content-between">

                                    <div class="cart_item_image">
                                        <a class="book_name" href="{{ book.get_absolute_url }}">
                                            <img src="{{ book.image.url }}" alt="{{ book.title }}">
                                        </a>
                                    </div>

                                    <div>
                                        <div class="cart_item_title">Название</div>
                                        <div class="cart_item_text">
                                            <a class="book_name" href="{{ book.get_absolute_url }}">
                                                {{ book.title|truncatechars:25 }}
                                            </a>
                                        </div>
                                    </div>

                                    <div>
                                        <div class="cart_item_title">Автор</div>
                                        <div class="cart_item_text">
                                            <a class="book_name" href="{{ book.get_author_url }}">
                                                {{ book.author }}
                                            </a>
                                        </div>
                                    </div>

                                    <div>
                                        <div class="cart_item_title">Количество</div>
                                        <div class="cart_item_text">
                                            <form action="{% url 'cart:cart_add' book.id %}" method="post">
                                                {{ item.update_quantity_form.quantity }}
                                                {{ item.update_quantity_form.update }}
                                                <input class="btn btn-outline-secondary" type="submit" value="Обновить">
                                                {% csrf_token %}
                                            </form>
                                        </div>
                                    </div>


                                    <div>
                                        <div class="cart_item_title">Цена</div>
                                        <div class="cart_item_text">{{ item.total_price }} руб.</div>
                                    </div>


                                    <div>
                                        <a href="{% url 'cart:cart_remove' book.id %}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25"
                                                 fill="currentColor" class="bi bi-x-lg" viewBox="0 0 20 20">
                                                <path fill-rule="evenodd"
                                                      d="M13.854 2.146a.5.5 0 0 1 0 .708l-11 11a.5.5 0 0 1-.708-.708l11-11a.5.5 0 0 1 .708 0Z"/>
                                                <path fill-rule="evenodd"
                                                      d="M2.146 2.146a.5.5 0 0 0 0 .708l11 11a.5.5 0 0 0 .708-.708l-11-11a.5.5 0 0 0-.708 0Z"/>
                                            </svg>
                                        </a>
                                    </div>


                                </div>
                            </li>
                        </ul>
                    </div>
                    {% endwith %}
                    {% endfor %}

                    {% if cart %}
                    <div class="order_total">
                        <div class="text-md-right">
                            <div class="order_total_title">Итоговая стоимость</div>
                            <div class="order_total_amount">{{ cart.get_total_price }} руб.</div>
                        </div>
                    </div>
                    <div class="cart_buttons">
                        <a href="{% url 'catalog' %}" style="text-decoration: none">
                            <button type="button" class="button cart_button_clear">
                                Вернуться в каталог
                            </button>
                        </a>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'orders:order_create' %}">
                            <button type="button" class="button cart_button_checkout">
                                Перейти к оформлению
                            </button>
                        </a>
                        {% else %}
                        <a href="{% url 'login' %}">
                            <button type="button" class="button cart_button_checkout">
                                Перейти к оформлению
                            </button>
                        </a>
                        {% endif %}
                    </div>
                    {% else %}
                    <p class="fs-4">В корзине пусто.</p>
                        <a href="{% url 'catalog' %}">
                            <button type="button" class="button cart_button_clear">
                                Вернуться в каталог
                            </button>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}